// <auto-generated />
namespace EarthLink.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_TestCases_In_Exams : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_TestCases_In_Exams));
        
        string IMigrationMetadata.Id
        {
            get { return "201608131118072_Added_TestCases_In_Exams"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
